### ISSUE TITLE
`sink` command not found in standalone use

### ISSUE THREAD

**Issue by erxclau** [MichiganDaily/sink#1]
### Description

1. Clone this repository.
2. Install dependencies by running `yarn`.
3. Run `yarn sink godc`.

```shell
ericlau@Erics-MacBook-Air sink % yarn sink gdoc
yarn run v1.22.17
error Command "sink" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The README says to just run `sink gdoc` without `yarn` but this doesn't work either:

```shell
ericlau@Erics-MacBook-Air sink % sink gdoc
zsh: command not found: sink
```

This seems to arise in standalone use only. Running `sink` when it is included as a dependency in `cookie` works properly.

Is this the expected behavior? Why does running `sink` work in `cookie` as opposed to standalone use?

### Workaround

Running `node src/sink-gdoc.js` instead works properly.

### Details

My `yarn` version is 1.22.17. My `node` version is 17.0.1. My operating system is macOS Big Sur.

**Comment by naitian** [comment]
I think `yarn run sink gdoc` works if you don't install globally. If you install with `yarn global add sink`, `sink gdoc` should work.

**Comment by erxclau** [comment]
In the typical context where `sink` is a dependency of another repository, the first command you suggested works, and so does the first command from the original post. Thinking about it again, the premises in the original post actually seem somewhat contrived.

I believe the original context surrounding this issue had to do with the Alumni Directory. I will follow up with that team to see if they're still running into issues. Closing for now.

**Comment by erxclau** [comment]
Sidenote: I suppose this means that testing a local version of `sink` is going to involve more than trying to running a command. Probably have to symlink it? I'm assuming that what you did with the pull request is push to the `fetch-array` branch and then just install the latest commit as a dependency in a cookie instance? @naitian
